version: 2
formats:
  - htmlzip
  - pdf
python:
  version: 3.6
  install:
     - requirements: requirements.txt
build:
  image: stable
sphinx:
  builder: html
  configuration: conf.py
  fail_on_warning: false
