# Travis is only used to test the Sphinx build and is configured to fail on
# bad links and references. The actual docs are published on RTD which has its
# own webhook and is not related to anything that travis does.

dist: trusty
sudo: required
os: linux
env: LINUX=ubuntu:16.04
language: python
python: "3.4"

services:
  - docker

before_install:
  - git clone --recursive --branch ${TRAVIS_BRANCH} https://github.com/missionpinball/mpf.git /tmp/_mpf || git clone --recursive --branch dev https://github.com/missionpinball/mpf.git /tmp/_mpf;
  - git clone --recursive --branch ${TRAVIS_BRANCH} https://github.com/missionpinball/mpf-mc.git /tmp/_mpf-mc || git clone --recursive --branch dev https://github.com/missionpinball/mpf_mc.git /tmp/_mpf-mc;
  - git clone --branch ${TRAVIS_BRANCH} https://github.com/missionpinball/mpf-debian-installer.git /tmp/_mpf_installer || git clone --recursive --branch dev https://github.com/missionpinball/mpf-debian-installer.git /tmp/_mpf_installer;

install:
- pip3 install --upgrade coveralls

script:
    - docker run -v /dev/snd:/dev/snd -v /tmp/_mpf:/tmp/_mpf -v /tmp/_mpf-mc:/tmp/_mpf-mc -v /tmp/_mpf_installer:/tmp/_mpf_installer -v $PWD:$PWD -w $PWD $LINUX /bin/sh -c "/tmp/_mpf_installer/install-mpf-dependencies && /tmp/_mpf_installer/install-mc-dependencies && pip3 install -e /tmp/_mpf/ && pip3 install /tmp/_mpf-mc/ && pip3 install -q -r requirements.txt && sphinx-build -nW -b html -d _build/doctrees . _build/html";

# -n   Run in nit-picky mode, warn about all missing references.
# -W   Turn warnings into errors.
