# Travis is only used to test the Sphinx build and is configured to fail on
# bad links and references. The actual docs are published on RTD which has its
# own webhook and is not related to anything that travis does.

language: python
dist: trusty
sudo: required

python:
  - "3.4"

install:
  - "git clone --branch dev https://github.com/missionpinball/mpf-debian-installer.git _mpf_installer"
  - "sudo _mpf_installer/install-mpf-dependencies && sudo _mpf_installer/install-mc-dependencies"
  - "pip install -v -v -v -r requirements.txt"

script:
  - "sphinx-build -nW -b html -d _build/doctrees . _build/html"

# -n   Run in nit-picky mode, warn about all missing references.
# -W   Turn warnings into errors.
