language: python

python:
- "3.4"

install:
- git clone --recursive --branch ${TRAVIS_BRANCH} https://github.com/missionpinball/mpf.git ../_mpf || git clone --recursive --branch `python3 get_version.py` https://github.com/missionpinball/mpf.git ../_mpf || git clone --recursive --branch dev https://github.com/missionpinball/mpf.git ../_mpf
- pip3 install -e ../_mpf/

script:
- python3 -m unittest discover
