environment:

  matrix:
    - PYTHON: "C:\\Python27"

install:
  - "%PYTHON%\\python.exe -m pip install sphinx"
  - "%PYTHON%\\python.exe -m pip install sphinx_bootstrap_theme==0.4.9"

build: off

test_script:
  - "echo None"

after_test:
  - "make html"
  - "cd _build/html"
  - "rd _sources /q /s"

artifacts:
  - path: _build/html
    name: html

deploy:
  provider: Environment
  name: mpf-docs
